### PR TITLE
Add oauth-bundle

### PR DESCRIPTION
**Pull request by uxgood**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Pull request does not pass validation.

**Review by ghost — CHANGES_REQUESTED** [review]
Pull request does not pass validation.

**Review by ghost — CHANGES_REQUESTED** [review]
Pull request does not pass validation.

**Review by ghost — APPROVED** [review]
Pull request passes validation.

**Comment by uxgood** [comment]
merge

**Pull request merged**
